only compile babel once and keep compiled code in memory
jvatic/goja-babel pull request #3
Opened 2019-12-26 06:16 UTC by MagicalTux

rather than fetch/compile each time

This improve performances of Init() quite a bit, and cost is fairly low. Also, ensures babel.js compiles.

2019-12-26 13:15 UTC, jvatic requested changes
Thanks for your contribution! Please iterate on the requested changes and we can get this merged 🙂

2019-12-26 13:15 UTC, jvatic commented on babel.go
> +var babelProg = goja.MustCompile("babel.js", string(_MustAsset("babel.js")), false)
I'd prefer the compile step be done in the once function however and the error captured and retured if not nil. I also think it should be in strict mode unless that doesn't work.

i.e.

```go
// ...
var babelProg *Program

func Init(poolSize int) (err error) {
	once.Do(func() {
		babelSrc, err = _Asset("babel.js")
		if err != nil {
			return
		}
		babelProg, err = goja.Compile("babel.js", string(babelSrc), true)
		if err != nil {
			return
		}
		// ...
	})

	return err
}
// ...
```

2019-12-29 07:01 UTC, MagicalTux commented
Hi, the changes have been implemented.

Note that because it uses `sync.Once`, if the `Init()` method fails, calling it again will not result in an error but will not do anything. One option would be to reset the `sync.Once` object to a new one on failure, or use a simple lock and a different way to check if initialization is done.

2019-12-30 15:31 UTC, jvatic commented
@MagicalTux The assumption is any error which occurs in `Init` will result in the parent program exiting. I do think resetting the `sync.Once` before returning an error is a good idea. Thanks for pointing this out!

2019-12-30 15:33 UTC, jvatic approved these changes
LGTM! 👍

2019-12-30 15:34 UTC, merged

2019-12-30 15:40 UTC, jvatic commented
@MagicalTux Your changes unfortunately broke the existing test suite. Please open a new PR once the tests are passing.

2020-01-02 02:26 UTC, MagicalTux commented
@jvatic Tested locally and the issue comes from enabling strict mode. Branch has been updated to disable strict mode.

2020-01-02 15:29 UTC, jvatic commented
@MagicalTux Thanks! Merged again.